# Generated by Django 3.0.8 on 2020-07-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shutter', '0002_auto_20200727_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='photos',
            new_name='photo',
        ),
    ]
