# Generated by Django 3.0.8 on 2020-07-27 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shutter', '0004_auto_20200727_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='shutter.Album'),
            preserve_default=False,
        ),
    ]
